### Obtener token 
POST https://rest.contabilium.com/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=rodrihaag@gmail.com&client_secret=e7bb9bd7c18546a483d009dcb85d1ca7

### Obtener productos 
GET https://rest.contabilium.com/api/conceptos/search?pageSize=50
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer A07RKRrnAkUfhHOia6BZ4VLL6uWRFyyODapVE_p-STglkQE9R9ygmLRhUlHFXwrua_OpB7cR-v-1xhfPZ7CnFwJcltpVG54iEH9DnfwaoH7bXvhsHdww_oWzqkOXGVZOL1vnoHQD2PABH9tjz7-IIk8Tl-Vh5gPf66STiNV-cg9Res1PaARA137A4y-0tqXHf1G73UwYWEF0Tlhshv5IFksvUKLfm5-rTdGV613aRQi3p1ggd4DGEMfe83Z84cKezMI3wX_Mj9pj6uufHSCH-6IPi7Vq3VLm_r3u3bwZ9nlLU20CXOe_gD0qSI9Pjvtmt07dCjFI1tLPdSLK_kevQxR52Fli8ohF3oXAjU9on1FrKn2HaI46lO8qmDrmleMqsf6GOh-F2uxHQhVcvMSmv27icMNL8zF_W0j3R-rQQD1xEkuKbbudx2YyiJ6ZWEJDz_y-mKxZ05sPQl6A6wgSR2Q3O_ZGo75P04CxHyqmgj3AOSwb9lMDTUYQg1K6nnWrGB5Wv__PhpFLHHwBChzflzl0pQ3DFRfajFknMWdpwktB7Vz_CdF4A54N1eoJmczYV0S9P9_EASzPVxj8HbOXJsK83oQk0Iy5DogP6TJvTZVzd1Q3NGJB9IG2ZYj9LCVVsBe7nqEpkLKSAsA9VSvD1A

grant_type=client_credentials&client_id=rodrihaag@gmail.com&client_secret=e7bb9bd7c18546a483d009dcb85d1ca7

### Obtener categorías 
GET https://rest.contabilium.com/api/conceptos/rubros
Authorization: Bearer A07RKRrnAkUfhHOia6BZ4VLL6uWRFyyODapVE_p-STglkQE9R9ygmLRhUlHFXwrua_OpB7cR-v-1xhfPZ7CnFwJcltpVG54iEH9DnfwaoH7bXvhsHdww_oWzqkOXGVZOL1vnoHQD2PABH9tjz7-IIk8Tl-Vh5gPf66STiNV-cg9Res1PaARA137A4y-0tqXHf1G73UwYWEF0Tlhshv5IFksvUKLfm5-rTdGV613aRQi3p1ggd4DGEMfe83Z84cKezMI3wX_Mj9pj6uufHSCH-6IPi7Vq3VLm_r3u3bwZ9nlLU20CXOe_gD0qSI9Pjvtmt07dCjFI1tLPdSLK_kevQxR52Fli8ohF3oXAjU9on1FrKn2HaI46lO8qmDrmleMqsf6GOh-F2uxHQhVcvMSmv27icMNL8zF_W0j3R-rQQD1xEkuKbbudx2YyiJ6ZWEJDz_y-mKxZ05sPQl6A6wgSR2Q3O_ZGo75P04CxHyqmgj3AOSwb9lMDTUYQg1K6nnWrGB5Wv__PhpFLHHwBChzflzl0pQ3DFRfajFknMWdpwktB7Vz_CdF4A54N1eoJmczYV0S9P9_EASzPVxj8HbOXJsK83oQk0Iy5DogP6TJvTZVzd1Q3NGJB9IG2ZYj9LCVVsBe7nqEpkLKSAsA9VSvD1A
